version: 2.1

executors:
  default:
    docker:
      - image: alpine
    shell: /usr/bin/env bash -euo pipefail -c

commands:
  prep:
    steps:
      - run:
          shell: /bin/sh
          name: Install Dependencies
          command: apk add make bash bc
      - checkout

jobs:
  test-singles:
    executor: default
    steps:
      - prep
      - run: make test-singles
  test-alls:
    executor: default
    steps:
      - prep
      - run: make test-alls
  test:
    executor: default
    steps:
      - prep
      - run: make test

workflows:
  all:
    jobs:
      - test-singles
      - test-alls
      - test:
          requires:
            - test-singles
            - test-alls

