name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        bash_version: ["5.0.7", "3.2.57"]
    runs-on: ubuntu-latest
    container:
      image: bash:${{ matrix.bash_version }}
    steps:
      - uses: actions/checkout@master
      - run: bash --version
      - name: Test
        run: make test
