name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: make test
  test-bash-3.2.57:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://bash:3.2.57
        entrypoint: ["/usr/bash", "-euo", "pipefail", "-c", "make test"]
